# config.toml
[BASE_INFO]
# The app name will be applied to all processes including agent service integration.
appname = 'ob_dba_planning_agent'

[CORE_PACKAGE]
# Perform a full component scan and registration for all the paths under this list.
default = ['ob_dba_agent.ob_dba_agent.core']
# Further information is omitted here.
agent = ['ob_dba_agent.ob_dba_agent.core.agent']
planner = ['ob_dba_agent.ob_dba_agent.core.planner']
prompt = ['ob_dba_agent.ob_dba_agent.core.prompt']
knowledge = ['ob_dba_agent.ob_dba_agent.core.knowledge']
llm = ['ob_dba_agent.ob_dba_agent.core.llm']

[SUB_CONFIG_PATH]
# Custom key file path, use to save your own secret key like open ai or sth else. REMEMBER TO ADD IT TO .gitignore.
custom_key_path = './custom_key.toml'
# Further information is omitted here.